controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

toggle_theme:
    path: /toggle-theme
    controller: App\Controller\ThemeController::toggleTheme